#!/usr/bin/env python3
"""Render research/projection_v2/RESULTS.md and results_summary.json from the stored study outputs.

Every number in the report is read from a JSON file the analysis wrote; nothing is typed by hand.
"""
from __future__ import annotations

import json, os, sys

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "..", "research", "projection_v2")
TOURS = ("ATP", "WTA")
LEVEL_NAMES = {"GS": "Grand Slam", "M": "Masters 1000 / Finals / Olympics", "T": "Tour 250/500", "C": "Challenger / WTA 125",
               "I": "ITF", "O": "Team / other"}


def J(name):
    p = os.path.join(OUT, name)
    return json.load(open(p)) if os.path.exists(p) else None


def f4(x):
    return "--" if x is None else f"{x:.4f}"


def fd(d, k="brier"):
    ci = d.get(f"{k}_ci") or [None, None]
    return f"{d.get(f'{k}_diff', 0):+.5f} [{ci[0]:+.5f}, {ci[1]:+.5f}]"


def lanes_table(res, tour, names):
    L = ["| lane | n | Brier | log loss | accuracy | cal. slope | ECE | favourite-side intercept |", "|---|---|---|---|---|---|---|---|"]
    for n in names:
        v = res[tour]["lanes"].get(n)
        if v:
            L.append(f"| {n} | {v['n']} | {v['brier']:.4f} | {v['log_loss']:.4f} | {v['accuracy']:.4f} | {v['cal_slope']:.3f} | "
                     f"{v['ece']:.4f} | {v['fav_cal_intercept']:+.3f} |")
    return L


def main():
    ev, va, ho = J("results_evaluate.json"), J("results_validate.json"), J("results_holdout.json")
    dec, sel, fz = J("PROMOTION_DECISION.json"), J("selection_log.json"), J("FROZEN_CHALLENGER.json")
    dfix, der, mkt = J("DATA_FIX_DECISION.json"), J("derivatives_eval.json"), J("market_benchmark_v2.json")
    L = ["# Projection Engine V2 -- backtest results", "",
         "Generated by `scripts/research/projection_v2/write_report.py` from the stored study outputs in this directory. "
         "Protocol: `PREREGISTRATION.md` (committed before any challenger result). Every probability below is out of sample "
         "in time: ratings are replayed chronologically and the ensemble for season Y is fitted on seasons Y-6..Y-1 only.", "",
         "## Verdict", "",
         f"**{dec['verdict']}** -- preregistered rules P1-P8:", ""]
    L += ["| rule | result |", "|---|---|"] + [f"| {k} | {'PASS' if v else ('FAIL' if v is not None else 'n/a')} |" for k, v in dec["rules"].items()]
    L += ["", "P9 (operational) is verified separately: train/serve parity test, no-lookahead and market-import tests, the full test "
          "suite, RUN TENNIS runtime, and the live verification run (see the PR and `LIVE_VERIFICATION.md`).", "",
          "## The frozen challenger", "", "```json", json.dumps(fz["spec"], indent=1), "```", "",
          f"Fingerprint `{fz['spec_fingerprint']}`, frozen {fz['frozen_at']} on the 2016-2020 selection window.", "",
          "### Selection (2016-2020 only)", "", "Elo tournament (log loss, lower is better):", "",
          "| variant | pooled | ATP | WTA |", "|---|---|---|---|"]
    for k, v in sorted(sel["elo_tournament_2016_2020"].items(), key=lambda kv: kv[1]["pooled_ll"]):
        L.append(f"| {k}{' (incumbent Elo)' if k == 'E_prod' else ''} | {v['pooled_ll']:.5f} | {v['ATP_ll']:.5f} | {v['WTA_ll']:.5f} |")
    L += ["", "Greedy block selection (walk-forward stacker, 2016-2020 log loss):", "", "| step | pooled LL | ATP gain | WTA gain | kept |", "|---|---|---|---|---|"]
    for g in sel["greedy"]:
        gain = g.get("gain") or {}
        L.append(f"| {g['step']} | {g['pooled_ll']:.5f} | {gain.get('ATP', 0):+.5f} | {gain.get('WTA', 0):+.5f} | {g.get('kept', 'base')} |")
    for title, res in (("Evaluation window 2021-2024", ev), ("Validation 2021-2025 (2025 revealed once)", va), ("Holdout 2026 YTD (run once)", ho)):
        L += ["", f"## {title}", ""]
        for t in TOURS:
            L += [f"### {t}", ""] + lanes_table(res, t, ["INCUMBENT", "FAIR_V1", "ELO_PROD_RAW", next(n for n in res[t]["lanes"] if n.startswith("ELO_RAW")),
                                                       "ELO+PLATT", "CHALLENGER"])
            d = res[t]["vs_incumbent"]["CHALLENGER"]
            L += ["", f"Challenger - incumbent (paired, cluster bootstrap over {d['clusters']} tournament instances): "
                      f"Brier {fd(d)}, log loss {fd(d, 'll')}.", ""]
    L += ["", "## Season by season (Brier difference, challenger - incumbent)", "", "| season | ATP n | ATP diff [95% CI] | WTA n | WTA diff [95% CI] |", "|---|---|---|---|---|"]
    seasons = sorted(set(va["ATP"]["segments"]["season"]) | set(ho["ATP"]["segments"]["season"]))
    for s in seasons:
        row = [s]
        for t in TOURS:
            seg = (va[t]["segments"]["season"].get(s) or ho[t]["segments"]["season"].get(s))
            row += [str(seg["n"]), fd(seg["diff"])] if seg else ["--", "--"]
        L.append("| " + " | ".join(row) + " |")
    L += ["", "## Segments (2021-2025)", ""]
    for segname in ("level", "surface", "experience", "serve_evidence", "favourite_prob", "form_data"):
        L += [f"### by {segname.replace('_', ' ')}", "", "| tour | segment | n | incumbent Brier | challenger Brier | diff [95% CI] | challenger cal. slope |", "|---|---|---|---|---|---|---|"]
        for t in TOURS:
            for k, v in sorted(va[t]["segments"][segname].items()):
                name = LEVEL_NAMES.get(k, k) if segname == "level" else k
                L.append(f"| {t} | {name} | {v['n']} | {v['incumbent']['brier']:.4f} | {v['challenger']['brier']:.4f} | {fd(v['diff'])} | {v['challenger']['cal_slope']:.3f} |")
        L.append("")
    L += ["## Ablations (2021-2025, Brier difference vs incumbent)", "", "Leave one block out of the frozen challenger, and add blocks one at a time to the bare rating:", "",
          "| lane | ATP | WTA |", "|---|---|---|"]
    for name in [n for n in va["ATP"]["vs_incumbent"] if n.startswith(("ABLATE", "ADD", "ELO", "CHALLENGER", "FAIR"))]:
        L.append(f"| {name} | {fd(va['ATP']['vs_incumbent'][name])} | {fd(va['WTA']['vs_incumbent'][name])} |")
    L += ["", "## Calibration (favourite-oriented reliability, 2021-2025)", ""]
    for t in TOURS:
        L += [f"### {t}", "", "| favourite prob | n | incumbent mean p | incumbent win rate | challenger mean p | challenger win rate |", "|---|---|---|---|---|---|"]
        inc = {r["bucket"]: r for r in va[t]["reliability"]["INCUMBENT"]}
        ch = {r["bucket"]: r for r in va[t]["reliability"]["CHALLENGER"]}
        for b in sorted(set(inc) | set(ch)):
            a, c = inc.get(b, {}), ch.get(b, {})
            L.append(f"| {b} | {c.get('n', '--')} | {f4(a.get('mean_p'))} | {f4(a.get('win_rate'))} | {f4(c.get('mean_p'))} | {f4(c.get('win_rate'))} |")
        L.append("")
    L += ["## The data fix on its own (canonical_v1 -> canonical_v2, incumbent model)", "",
          f"Decision: **{dfix['decision']}** (seasons {dfix['seasons']}).", "", "| tour | v1 rows | v2 rows | v1 rows that were duplicates | Brier v2 - v1 [95% CI] |", "|---|---|---|---|---|"]
    for t in TOURS:
        d = dfix[t]
        L.append(f"| {t} | {d['v1_rows']} | {d['v2_rows']} | {d['v1_rows_not_in_v2_(removed_duplicates)']} | {fd(d['v2_minus_v1'])} |")
    L += ["", "## Derivative distributions (Workstream G)", "",
          "Completed matches with parsed scores; ranked probability score (RPS) for total games and game differential, log score for the exact set score, "
          "Brier for 'goes the distance' and for an over/under line. Lower is better everywhere.", "",
          "| window | tour | distribution | RPS total games | RPS game diff | log score set score | Brier distance | Brier over line |", "|---|---|---|---|---|---|---|---|"]
    for k, v in sorted(der["summary"].items()):
        w, t, var = k.split("|")
        L.append(f"| {w} | {t} | {var} | {v['rps_total_games']:.5f} | {v['rps_game_diff']:.5f} | {v['ll_set_score']:.5f} | {v['brier_distance']:.5f} | {v['brier_over_line']:.5f} |")
    L += ["", f"Service-level rule chosen on 2023-2024: **{der['chosen_on_selection_window']}**.", ""]
    if mkt:
        L += ["## Market benchmark (computed AFTER the freeze; cannot change the model)", "",
              f"ATP main tour, Pinnacle (vig-free, tennis-data.co.uk) on {mkt['n_linked']} linked matches, seasons {mkt['seasons']}.", "",
              "| forecaster | Brier | log loss | cal. slope |", "|---|---|---|---|"]
        for k, v in mkt["scores"].items():
            L.append(f"| {k} | {v['brier']:.4f} | {v['log_loss']:.4f} | {v['cal_slope']:.3f} |")
        L += ["", f"V2 - Pinnacle: {fd(mkt['v2_minus_pinnacle'])}; incumbent - Pinnacle: {fd(mkt['incumbent_minus_pinnacle'])}; "
              f"V2 - incumbent on these matches: {fd(mkt['v2_minus_incumbent_on_linked'])}.", "",
              "Disagreement buckets -- when V2 and Pinnacle disagree, whose number does the result follow?", "",
              "| |V2 - market| | n | V2 side, V2 says | V2 side, market says | V2 side actually won |", "|---|---|---|---|---|"]
        for k, v in mkt["disagreement_buckets"].items():
            L.append(f"| {k} | {v['n']} | {v['v2_side_implied_by_v2']:.3f} | {v['v2_side_implied_by_market']:.3f} | {v['v2_side_actual_win_rate']:.3f} |")
        L += ["", "Information beyond the market (walk-forward logistic regression on both logits; diagnostic only):", "",
              "| season | weight market | weight V2 | Brier combined | Brier market | n |", "|---|---|---|---|---|---|"]
        for s, v in mkt["information_beyond_market"].items():
            L.append(f"| {s} | {v['weight_market']:.3f} | {v['weight_v2']:.3f} | {v['brier_combined']:.4f} | {v['brier_market']:.4f} | {v['n']} |")
        L += ["", "Reading: V2 closes part of the gap to the sharp market but the market remains clearly better, and the combination never "
              "beats the market alone out of sample -- at tour level V2 carries essentially no information the market lacks. Large "
              "V2-market disagreements are mostly V2 error. This is the honest answer to 'how much independent information are we missing': "
              "most of it is what free, lagging results data cannot carry (injury/withdrawal news, current form beyond the data horizon).", ""]
    open(os.path.join(OUT, "RESULTS.md"), "w").write("\n".join(L) + "\n")
    summary = {"verdict": dec["verdict"], "rules": dec["rules"], "spec": fz["spec"], "spec_fingerprint": fz["spec_fingerprint"],
               **{f"{t}_{w}": {"incumbent": r[t]["lanes"]["INCUMBENT"], "challenger": r[t]["lanes"]["CHALLENGER"],
                              "diff": r[t]["vs_incumbent"]["CHALLENGER"]} for t in TOURS for w, r in (("2021_2024", ev), ("2021_2025", va), ("2026_holdout", ho))},
               "data_fix": {t: dfix[t]["v2_minus_v1"] for t in TOURS}, "derivatives_choice": der["chosen_on_selection_window"],
               "market_benchmark": {k: mkt[k] for k in ("n_linked", "v2_minus_pinnacle", "incumbent_minus_pinnacle")} if mkt else None}
    json.dump(summary, open(os.path.join(OUT, "results_summary.json"), "w"), indent=1, default=float)
    print("wrote RESULTS.md and results_summary.json")


if __name__ == "__main__":
    main()
